
###
post http://localhost:3000/login
Content-Type: application/json

{
    "username":"Kang2001",
    "password":"1234_abcd"
}

###
post http://localhost:3000/login/security
Content-Type: application/json

{
    "username":"Siti",
    "password":"b022124"
}


###
post http://localhost:3000/register/admin
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkthbmcyMDAxIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzA0NDYxMTE2LCJleHAiOjE3MDQ0NjE3MTZ9.OGa96cAXgKXx3H5M3ptcihfMIM9r5BcGEeUHbfu40DM
Content-Type: application/json

{
    "username":"Amni",
    "password":"d02221",
    "email":"amni@gmail.com"
} 

###
post http://localhost:3000/register/security
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkthbmcyMDAxIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzA0NDczMzAxLCJleHAiOjE3MDQ0NzM5MDF9.wrJgY6OHhzlfkPzsQnEMdJwqYzWQnOWLJVkFBHxI-Ho
Content-Type: application/json

{
    "username":"Abby",
    "password":"d02221",
    "email":"abby@gmail.com"
} 


// sini

###
post http://localhost:3000/create/visitor/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkthbmcyMDAxIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzA0NDYyMTAyLCJleHAiOjE3MDQ0NjI3MDJ9.XWqmR9NQ8b6VkNB9VqTaX_vqBIZhYqEIOFmQCjpbsko
Content-Type: application/json

{
    "visitorname": "Hee",
    "timespend":"1",
    "age":"18",
    "phonenumber":"0126531012"
}


//sini

###
post http://localhost:3000/create/test/visitor
Content-Type: application/json

{
    "visitorname": "Dr Lim",
    "idproof": "5678",
    "entrytime":"1045",
    "approval": "yes"
}

###
GET http://localhost:3000/view/visitor/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXIiLCJpYXQiOjE3MDQwOTkyNTgsImV4cCI6MTcwNDA5OTg1OH0.SCvTyAWKI7ZIepogvkeTktUCZ_pPbSYHqaXlzoX2AYQ


###
GET http://localhost:3000/view/test/visitor/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXIiLCJpYXQiOjE3MDQwOTkyNTgsImV4cCI6MTcwNDA5OTg1OH0.SCvTyAWKI7ZIepogvkeTktUCZ_pPbSYHqaXlzoX2AYQ


###
DELETE http://localhost:3000/delete/visitor/5678
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXIiLCJpYXQiOjE3MDM0MTcwMTMsImV4cCI6MTcwMzQxNzYxM30.EpkbihyKjKazLHI9HHNaiqNQIMoZIUTikmMc4B0d800
Content-Type: application/json

{
    "idproof": "5678"
}




//Visitor log

###
post http://localhost:3000/create/visitorlog/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXIiLCJpYXQiOjE3MDM0MTcwMTMsImV4cCI6MTcwMzQxNzYxM30.EpkbihyKjKazLHI9HHNaiqNQIMoZIUTikmMc4B0d800
Content-Type: application/json

{
    "visitorname": "dr khoo",
    "idproof": "d123",
    "timespend": 3,
    "payment": 12
}

###
GET http://localhost:3000/view/visitorlog/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXIiLCJpYXQiOjE3MDM0MTcwMTMsImV4cCI6MTcwMzQxNzYxM30.EpkbihyKjKazLHI9HHNaiqNQIMoZIUTikmMc4B0d800
Content-Type: application/json


###
POST http://localhost:3000/create/computer
Content-Type: application/json

{
    "idproof": "b0123", 
    "lanportno": 31738124,
    "available": "yes"
}

###
GET http://localhost:3000/view/computer/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXIiLCJpYXQiOjE3MDM0MTcwMTMsImV4cCI6MTcwMzQxNzYxM30.EpkbihyKjKazLHI9HHNaiqNQIMoZIUTikmMc4B0d800

